services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # 백엔드 API URL 환경변수 (필요시 수정)
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api